##################################################
### Install packages
- name: Add apt key
  become: true
  apt_key: url={{ item }} state=present
  with_items:
    - "{{ vscode_repository_key }}"

- name: Add repository
  become: true
  apt_repository: repo="deb [arch=amd64] {{ vscode_repository }} stable main" state=present update_cache=yes

- name: Install packages
  become: true
  apt: name={{ item }} state=present
  with_items:
    - code

- name: Install extensions
  shell: code --install-extension {{ item }}
  with_items:
    - haaaad.ansible
    - timonwong.ansible-autocomplete
    - therealmarv.vscode-theme-dark-atom-dark-green-cursor
    - robertohuertasm.vscode-icons
    - waderyan.gitblame
    - donjayamanne.githistory